version: '3'

services:
    ssh-tarpit:
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        volumes:
            - '${PWD}/logs:/usr/src/app/logs'
        ports:
            - '22:22'
            - '8080:8080'
